// Auto-generated seed data from CHECKLISTS CAROLDO.xlsx
// Source: /home/z/my-project/upload/CHECKLISTS CAROLDO.xlsx

export const POSTOS = [
  { nome: "Eletricista", corCapacete: "Laranja" },
  { nome: "Instalador Hidráulico", corCapacete: "Azul" },
  { nome: "Marceneiro", corCapacete: "Amarelo" },
  { nome: "Pedreiro", corCapacete: "Azul" },
  { nome: "Pintor", corCapacete: "Amarelo" },
  { nome: "Servente de Obras", corCapacete: "Verde" },
  { nome: "Supervisor", corCapacete: "" },
  { nome: "Técnico de Infraestrutura de Redes", corCapacete: "Laranja" },
  { nome: "Técnico de Refrigeração", corCapacete: "Amarelo" },
] as const;

export const CATEGORIAS = [
  { nome: "Materiais", descricao: "Ferramentas e materiais permanentes por posto" },
  { nome: "EPI", descricao: "Equipamentos de Proteção Individual por posto" },
  { nome: "Uniforme", descricao: "Uniformes entregues aos terceirizados" },
  { nome: "Documento", descricao: "Documentação admissional e legal" },
] as const;

// Itens por (categoria, posto) — lista de descrições
export const ITENS_POR_POSTO: Record<string, string[]> = {
  "Documento__Eletricista": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "Documento__Instalador Hidráulico": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "Documento__Marceneiro": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "Documento__Pedreiro": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "Documento__Pintor": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "Documento__Servente de Obras": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "Documento__Supervisor": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "Documento__Técnico de Infraestrutura de Redes": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "Documento__Técnico de Refrigeração": [
    "Cópia da folha dos posto de trabalho",
    "Cópia da carteira de trabalho",
    "Cópia do contrato",
    "Cópia do ASO",
    "Cópia da carteira de vacinação (COVID)",
    "Cópia da carteira de vacinação (ANTITETÂNICA)",
    "Cópia PGR  ou  PPRA e PCMSO",
    "Cópia das Normas 05, 07, 10, 12, 23, 33 e 35",
    "Cópia de Cursos Técnicos / Especializações",
  ],
  "EPI__Eletricista": [
    "Capacete de Segurança, com jugular, na cor laranja",
    "Botina NR 10",
    "Luva tátil EN 1149",
    "Luva modelo vaqueta (couro)",
    "Luva isolante até o antebraço NBR 16295",
    "Óculos de segurança incolor",
    "Cinto de Segurança",
  ],
  "EPI__Instalador Hidráulico": [
    "Capacete de Segurança, com jugular, na cor azul",
    "Botina NR 10",
    "Luva de borracha nitrílica",
    "Luva modelo vaqueta (couro)",
    "Luva tátil EN 1149",
    "Luva de latéx",
    "Luva modelo de raspa (couro)",
  ],
  "EPI__Marceneiro": [
    "Capacete de Segurança, com jugular, na cor amarelo",
    "Botina NR 10",
    "Luva de vaqueta",
    "Luva tátil EN 1149",
    "Óculos de segurança incolor",
    "Respirador semifacial PFF2, N95",
  ],
  "EPI__Pedreiro": [
    "Capacete de Segurança, com jugular, na cor azul",
    "Óculos de segurança incolor",
    "Óculos de segurança preto fumê",
    "Botina NR 10",
    "Luva modelo vaqueta (couro)",
    "Luva de borracha nitrílica e algodão",
    "Luva tátil EN 1149",
    "Máscara semifacial com filtro para vapores orgânicos e ácidos.",
    "Cinto de segurança",
  ],
  "EPI__Pintor": [
    "Capacete de Segurança, com jugular, na cor amarelo",
    "Macacão para proteção química",
    "Luva de borracha e algodão",
    "Botina NR 10",
    "Óculos de segurança incolor",
    "Respirador semifacial PFF2, N95",
    "Luva de latéx",
    "Máscara semifacial com filtro para vapores orgânicos e ácidos.",
    "Cinto de segurança",
  ],
  "EPI__Servente de Obras": [
    "Capacete de Segurança, com jugular, na cor verde",
    "Óculos contra impacto incolor",
    "Óculos contra impacto preto fumê",
    "Botina NR 10",
    "Luva modelo vaqueta (couro)",
    "Luva nitrílica e algodão",
    "Luva de segurança tátil",
    "Cinto de Segurança",
  ],
  "EPI__Supervisor": [
    "Capacete de Segurança",
    "Botina NR 10",
    "Luva tátil EN 1149",
    "Cinto de segurança",
  ],
  "EPI__Técnico de Infraestrutura de Redes": [
    "Capacete de Segurança, com jugular, na cor laranja",
    "Botina NR 10",
    "Luva tátil EN 1149",
    "Luva modelo vaqueta (couro)",
    "Óculos contra impacto incolor",
    "Cinto de segurança",
  ],
  "EPI__Técnico de Refrigeração": [
    "Capacete de Segurança, com jugular, na cor amarelo",
    "Botina NR 10",
    "Luva tátil EN 1149",
    "Luva modelo vaqueta (couro)",
    "Óculos contra impacto incolor",
    "Cinto de segurança",
  ],
  "Materiais__Eletricista": [
    "Caixa de ferramentas metálica com 05 compartimentos, tratamento antiferrugem, pintura de alta resistência a pó. Medidas aproximadas 50x20x21 cm",
    "Alicate universal, acabamento polido, cabo ergonômico emborrachado com abas protetoras. Fabricado em aço carbono, 12”",
    "Alicate cortador e descascador de fios com crimpador",
    "Caneta detector de tensão alerta sonoro e luminoso, 12 v a 1000 V AC",
    "Identificador de circuitos elétricos com faixa mínima de operação 110v a 127 v",
    "Estilete profissional retrátil trapezoidal",
    "Alicate de corte diagonal 6\", indicado para cortar e desencapar fios e cabos elétricos com cabo isolado antiderrapante (ranhurado)",
    "Jogo de 8 chaves Fenda com isolamento elétrico 1000 V. Nos tamanhos: 1/8x3, 1/8x4, 3/16x3, 3/16x4, 3/16x6, 1/4x4, 1/4x6, 5/16x6",
    "Jogo de 8 chaves Philips com isolamento elétrico 1000 V. Nos tamanhos: 1/8x3, 1/8x4, 3/16x3, 3/16x4, 3/16x6, 1/4x4, 1/4x6, 5/16x6",
    "Chave Phillips Cotoco PHO 1/4 x 1.1/2 Polegadas",
    "Trena métrica metálica de 5 metros",
    "Alicate de bico reto 6\", indicado para o manuseio de terminais em instalações elétricas e corte de fios e arames macios; possui cabo isolado antiderrapante",
    "Arco de serra regulável. Lâmina de 12\". Acabamento cromado, cabo ergonômico injetado em polipropileno",
    "Martelo de borracha com cabo em madeira envernizada. Medidas: cabeça 80 mm e comprimento 320 mm",
    "Capa de Chuva em Nylon (parte externa poliamida e parte interna revestida em PVC)",
    "Jogo de Chaves Allen Longa de 3 a 10 mm com 08 Peças, forjados em aço cromo-vanádio; acabamento oxidado que protege contra a corrosão",
    "Conjunto jogo de chaves L cachimbo 5/16” a 9/16”",
    "Jogo completo de cachimbo 12 a 32 mm, em cromo vanádio",
    "Jogo de Chave Combinadas de 06 a 36 mm; Dois lados distintos (boca e estrela)",
    "Rotulador eletrônico portátil a pilha, fitas nas cores pretas, brancas e vermelhas",
    "Jogo de serra copo para ferro de ½” a 3”",
    "Voltímetro/amperímetro digital, tipo alicate, 750V/400A. CAT III",
    "Furadeira e Parafusadeira a bateria 18 v",
    "Jogo de Bits longo para parafusadeira com 2 Bits fenda e 2 Bits philips",
    "Jogo de Bits longo para parafusadeira Soquete Canhão de 5 A 13mm Magnetico",
    "Furadeira de impacto 440W/220V com brocas 4, 6, 8 e 10",
    "1 jogo de brocas aço rápido de 3mm à 12 mm",
    "1 jogo de brocas videa de 5mm à 12 mm",
    "Serra Sabre 28mm 1010W",
    "Radio comunicador freqüência 25 KHz, com fone, 400-470 MHz",
    "Escada extensiva 07 degraus alumínio NBR 13430  – RTG 615/ RAC 616",
    "Escada tipo tesoura de fibra 12 degraus, pés emborrachados",
    "Escada extensiva de fibra de vidro, 24 degraus, carga 120kg, altura aberta 8 m",
    "Kit com 4 pedestal haste com corrente, zebrado em amarelo e preto",
    "Bolsa tipo mala em lona para ferramentas eletricista, tamanho mínimo 16 polegadas",
    "Passa fio com alma 30 metros",
    "Lanterna de cabeça ou capacete, com bateria recarregável bivolt, mínimo 3 níveis de luminosidade, ajustável",
    "Lanterna recarregável bivolt, mínimo 9 leds, 54 lúmens, alcance 70 metros, comprimento 20cm",
    "Cartucheira cinto bolsa porta ferramentas",
  ],
  "Materiais__Instalador Hidráulico": [
    "Caixa de ferramentas metálica com 05 compartimentos, tratamento antiferrugem, pintura de alta resistência a pó. Medidas aproximadas 50x20x21 cm",
    "Chave Grifo de 14” – 350mm, produzida em aço carbono",
    "Chave Grifo de 18” – 450mm, produzida em aço carbono",
    "Chave Grifo de 24” – 600mm, produzida em aço carbono",
    "Chave Grifo de 36” – produzida em aço carbono",
    "Chave de Corrente para Tubos 5”. Em aço especial, empunhadura plastificada",
    "Engraxateria manual com acionamento por alavanca",
    "Jogo de Chave Combinadas de 06 a 36 mm; Dois lados distintos (boca e estrela), bocas fixas e estriadas com inclinação de 15º em relação ao corpo",
    "Pá de corte com cabo de madeira. Tamanho da pá (AxL): 28,5 x 20 cm ; Tamanho do cabo: 74 cm",
    "Pá de concha quadrada com cabo de madeira tamanho: 71 cm",
    "Picareta lamina numero 4 com olho oval 70x45 cm, com cabo de madeira 90 cm",
    "Torno/ Morsa de Bancada Grande",
    "Enxada larga com cabo de 130 cm",
    "Desentupidora elétrica para tubulação; Desobstrução mínima 1 ½, máxima 4\"",
    "Marreta oitavada 1 kg, com cabo de madeira",
    "Marreta oitavada 2 kg, com cabo de madeira",
    "Alicate de bico reto 6\", indicado para o manuseio de terminais em instalações elétricas e corte de fios e arames macios; possui cabo isolado antiderrapante",
    "Alicate de pressão profissional 10 polegadas, fabricado em aço carbono",
    "Maçarico a gás butano de pressão, temp. máxima 1200°C, com botão de ignição",
    "Talha manual de corrente, freio de haste dupla, apoio reforçado, 5m e 1 ton.",
    "Furadeira de impacto 440W/220V com brocas 4, 6, 8 e 10",
    "Lima grosa para madeira meia cana 200 mm com cabo ergonômico e emborrachado",
    "Alicate universal, acabamento polido, cabo ergonômico emborrachado com abas protetoras. Fabricado em aço carbono, medida 8\"",
    "Chave grifo para lavatório (formiga), possui mordentes em liga de aço forjado",
    "Chave ajustável inglesa 12”",
    "Chave de fenda 1/4 x 10. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave de fenda 3/16 x 7. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave de fenda 1/8 x 5. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave Philips 1/4 x 10. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave Philips 3/16 x 7. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave Philips 1/8 x 5. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Ponteira de aço redonda 5/8 x 10",
    "Talhadeira com corpo em aço, ponta em carboneto de tungstênio (metal duro) e encaixe SDS Plus",
    "Arco de serra regulável. Lâmina de 12\". Acabamento cromado, cabo ergonômico injetado em polipropileno",
    "Trena métrica metálica de 5 metros",
    "Capa de Chuva em Nylon (parte externa poliamida e parte interna revestida em PVC)",
    "Desentupidor de vaso sanitário com cabo de madeira 60 cm",
    "Desentupidor de pia sanfonado",
    "Chave multifuncional, como chave para porcas 40 mm, 34 mm, 28 mm, 23,5 mm, e 21 mm, porcas plásticas, sistema de nível, extrator de rosca quebrada",
    "Jogo de Chaves Allen Longa de 3 a 10 mm com 08 Peças, forjados em aço cromo-vanádio; acabamento oxidado que protege contra a corrosão",
    "Chave para retirada de válvula Hydra, com no mínimo 03 (três) adaptadores",
    "Jogo de tarraxa BSPT de ¼\", ½\", ¾\", 1” e 1.1/4”",
    "Alicate bico de papagaio n°10 com ranhura, cabo emborrachado, produzido em aço forjado",
  ],
  "Materiais__Marceneiro": [
    "Caixa de ferramentas metálica com 05 compartimentos, tratamento antiferrugem, pintura de alta resistência a pó. Medidas aproximadas 50x20x21 cm",
    "Plaina elétrica profissional 82mm, 700W, 220v, com lâmina e saco coletor",
    "Esquadro com cabo de alumínio e lâmina de aço inox. Com cabo projetado para uso a 45º, espessura da escala com 1,2mm e graduação em milímetros. Dimensão: 16” - 400 mm",
    "Nível com estrutura de madeira de alta resistência, escala métrica, tamanho: 12\" (304mm) e bolhas precisas de leitura: vertical, horizontal e 45°",
    "Prumo 500gr com corpo em aço revestido por plástico. Calço guia de madeira e cordão de náilon. Peso: 500g",
    "Escala métrica de madeira com graduação em mm/pol. Medida da escala: 2 metros",
    "Chave de fenda 1/8 x 05. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave de fenda 3/16 x 06. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave de fenda 5/16 x 08. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave Philips 1/8 x 05. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave Philips 3/16 x 06. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave Philips 5/16 x 08. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Jogo de Chaves Allen Torkx Longa de T10 a T50, 9 Peças, forjados em aço cromo-vanádio; acabamento oxidado que protege contra a corrosão",
    "Jogo de chave Allen de 3 a 10 mm, modelo longo, forjado em aço cromo-vanádio e acabamento oxidado",
    "Trena métrica metálica de 5 metros",
    "Lápis marcenaria",
    "Formão 10 mm com cabo em madeira envernizada e lâmina em aço (65 Mn). Espessura da lâmina do formão: 4,4 mm",
    "Formão 15 mm com cabo em madeira envernizada e lâmina em aço (65 Mn). Espessura da lâmina do formão: 4,4 mm",
    "Formão 20 mm com cabo em madeira envernizada e lâmina em aço (65 Mn). Espessura da lâmina do formão: 4,4 mm",
    "Martelo Unha/Carpinteiro 29 mm. Cabeça forjada em aço e cabo forjado em madeira envernizada",
    "Martelo de borracha com cabo em madeira envernizada. Medidas: cabeça 80 mm e comprimento 320 mm",
    "Pé de cabra simples 60 cm. Corpo em aço carbono, acabamento com pintura na cor preta e têmpera por indução nas extremidades",
    "Lima grosa para madeira meia cana 200 mm com cabo ergonômico e emborrachado",
    "Pedra para afiar com grão abrasivo carbeto de silício formato retangular. Espessura do grão abrasivo: lado grosso grão 120/ lado fino grão 240",
    "Torquês de carpinteiro com corpo forjado em aço especial. Acabamento com pintura eletrostática. Comprimento: 8\"",
    "Serrote 12” profissional, corta nos 2 sentidos, lâmina de aço SAE 1070 temperada, dentes travados e polidos",
    "Alicate universal, acabamento polido, cabo ergonômico emborrachado com abas protetoras. Fabricado em aço carbono, medida 8\"",
    "Rebitador manual profissional. Bocal estendido, com chave inclusa na alça, cabo com mola ejeta a haste do rebite e estrutura em aço reforçado",
    "Arco de serra regulável. Lâmina de 12\". Acabamento cromado, cabo ergonômico injetado em polipropileno",
    "Estilete profissional retrátil trapezoidal",
    "Jogo de serra copo de madeira com 11 peças",
    "Serra circular manual elétrica 9.¼ 1650W",
    "Jogo de brocas videa 3 mm à 12 mm",
    "Jogo de brocas para madeira 3mm à 10 mm",
    "Furadeira e Parafusadeira a bateria 18v",
    "Jogo de Bits longo para parafusadeira com 2 Bits fenda e 2 Bits philips",
    "Cabo extensor para furadeira flexível",
    "Furadeira de impacto 440W/220V com brocas 4, 6, 8 e 10",
    "Serra mármore 1500 W e discos",
    "Kit disco para esmerilhadeira, 4 discos corte madeira, 4 discos corta concreto, 4 discos corta ferro",
    "Grampeador de madeira para grampos de 04 mm a 14 mm",
    "Grampo tipo sargento mínimo 300x50x355 mm",
    "Serra de bancada móvel 10\"  220 v",
    "Nível e prumo a laser alcance mínimo 12m com suporte altura mínima 2m",
    "Serra tico-tico 500 W, com jogo de lâminas",
    "Tupia elétrica profissional 6mm e 8mm, 900W, 220v, com jogo de fresas.",
  ],
  "Materiais__Pedreiro": [
    "Colher de Pedreiro n°6 com Haste Curva e Cabo de Madeira envernizada",
    "Colher de Pedreiro n°8 com Haste Curva e Cabo de Madeira envernizada",
    "Martelo Unha/Carpinteiro 29 mm. Cabeça forjada em aço e cabo forjado em madeira envernizada",
    "Prumo de aço carbono com calço guia em madeira e cordão nylon de 2 metros",
    "Nível com estrutura de madeira de alta resistência, escala métrica, tamanho: 12\" (304mm) e bolhas precisas de leitura: vertical, horizontal e 45°",
    "Chave de fenda 5/16 x 06. Cabo em PVC injetado diretamente sob a lâmina e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Serrote 24 com lâmina larga em aço, dentes temperados e travados com 02 arestas cortantes. Cabo plástico com empunhadura ergonômica com revestimento de borracha",
    "Alicate universal, acabamento polido, cabo ergonômico emborrachado com abas protetoras. Fabricado em aço carbono, medida 8\"",
    "Mangueira para nível 10 metros fabricada em PVC cristal",
    "Marreta de 01 kg com cabo de madeira envernizado e ponteiro redondo",
    "Capa de Chuva em Nylon (parte externa poliamida e parte interna revestida em PVC), comprimento longo, capuz fixo ajustado por cordão, fechamento frontal com zíper e sobre lapa afixada por velcro, punhos com acabamento reto",
    "Desempenadeira de aço lisa com cabo de madeira envernizada e com uma haste de fixação",
    "Torquês de carpinteiro com corpo forjado em aço especial. Acabamento com pintura eletrostática. Comprimento: 8\"",
    "Desempenadeira de aço dentada 24cm x 12cm",
    "Desempenadeira com esponja",
    "Desempenadeira PVC frisada",
    "Martelo de borracha 80 mm com cabo de madeira",
    "Caixa para argamassa 20 litros",
    "Pá de concha quadrada com cabo de madeira; Tamanho do cabo: 71 cm",
    "Picareta lamina numero 4 com olho oval 70x45 cm, com cabo de madeira 90 cm",
    "Pá de corte com cabo de madeira Pá de corte com cabo de madeira  Tamanho da pá (AxL): 28,5 x 20 cm ; Tamanho do cabo: 74 cm",
    "Enxada larga com cabo de 130 cm",
    "Carrinho de mão tipo caçamba",
    "Régua de alumino para pedreiro 2,00 metros",
    "Talhadeira com corpo em aço especial, ponta em carboneto de tungstênio (metal duro) e encaixe SDS Plus",
    "Talhadeira 10 polegadas, forçada em aço carbono com empunhadura",
    "Trena métrica metálica de 5 metros",
    "Esquadro com cabo de alumínio. Com cabo projetado para uso a 45º, escala com 1,2mm e graduação em milímetros. Dimensão: 16” - 400 mm",
    "Balde de pedreiro em aço 10 litros",
    "Cortador de piso cerâmico 63x16x9 cm",
    "Furadeira de impacto 800W/220V SDS-PUS, com brocas 4, 6, 8 e 10, ponteira e talhadeira engate rápido.",
    "Martelo Rompedor de concreto 1600W 220v, SDS-PLUS, com brocas ponteira e talhadeira",
    "Esmerilhadeira angular 700 W",
    "Kit disco para esmerilhadeira, 4 discos corte madeira, 4 discos corta concreto, 4 discos corta ferro",
    "Serra mármore 1500 W e disco",
  ],
  "Materiais__Pintor": [
    "Caixa de ferramentas metálica com 05 compartimentos, tratamento antiferrugem, pintura de alta resistência a pó. Medidas aproximadas 50x20x21 cm",
    "Espátula profissional de aço forjado n°08, com cabo de madeira",
    "Espátula rígida n°12, com cabo de madeira",
    "Rolo de espuma, poliéster, n°09",
    "Rolo de espuma, poliéster, n°15",
    "Rolo de lã de carneiro, 25 cm",
    "Pincel 2 ½”",
    "Pincel 4”",
    "Chave de fenda 5/16 x 06. Cabo em PVC e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Chave Philips 5/16 x 06. Cabo em PVC e haste em aço 6150 (cromo vanádio) trefilado com acabamento: niquelado e polido",
    "Alicate de bico reto 6\", indicado para o manuseio de terminais em instalações elétricas e corte de fios e arames macios; confeccionado em aço cromo vanádio; possui cabo isolado antiderrapante (ranhurado)",
    "Trincha para pintura 20 cm",
    "Balde caçamba para pintura 15 litros",
    "Lixadeira manual em plástico 220mm x 80 mm",
    "Lixadeira manual em plástico com cabo. 22x19 cm",
    "Cabo extensor para pintura ajustável 3 metros, ponta tipo rosca",
    "Cabo extensor para pintura ajustável 5 metros, ponta tipo rosca",
    "Desempenadeira de aço lisa, 25,5 cm x 12 cm",
    "Kit desempenadeira de canto e quina",
    "Lixadeira elétrica orbital 200W tensão 220v, com bocal de sucção e saco coletor",
    "Andaime com peças em 2,00x2,00m, com 1,5 metros de altura, no mínimo 8 lances.",
    "Lixadeira de parede e teto 750 W com saco de aspiração, tensão 220v",
    "Compressor de ar elétrico completo, 220V, com pistola",
    "Escada extensiva 07 degraus alumínio, com pés emborrachado, ABNT NBR 13430  – RTG 615/ RAC 616",
    "Escada tipo tesoura de fibra 12 degraus, pés emborrachados.",
  ],
  "Materiais__Técnico de Infraestrutura de Redes": [
    "Caixa de ferramentas metálica com 05 compartimentos, 50x20x21 cm",
    "Bolsa tipo mala em lona para ferramentas, tamanho mínimo 16 polegadas.",
    "8 chaves Fenda: 1/8x3, 1/8x4, 3/16x3, 3/16x4, 3/16x6, 1/4x4, 1/4x6, 5/16x6",
    "8 chaves Philips: 1/8x3, 1/8x4, 3/16x3, 3/16x4, 3/16x6, 1/4x4, 1/4x6, 5/16x6",
    "Arco de serra regulável. Lâmina de 12\". Cabo ergonômico",
    "Furadeira e Parafusadeira a bateria 18V",
    "Jogo de Bits longo para parafusadeira com 2 Bits fenda e 2 Bits philips",
    "Furadeira de impacto 440W/220V com brocas 4, 6, 8 e 10",
    "Chave Teste Neon 135mm",
    "Alicate de corte diagonal 6\", com isolamento elétrico",
    "Trena métrica metálica de 5 metros",
    "Alicate universal, cabo ergonômico emborrachado. Em aço carbono, 12”",
    "Alicate cortador e descascador de fios com crimpador",
    "Caneta detector de tensão alerta sonoro e luminoso, 12 v a 1000 V AC",
    "Alicate crimpador RJ11 e RJ45",
    "Alicate crimpador RG59 e RG6 EBNC",
    "Alicate decapador giratório",
    "Alicate decapador HT501A",
    "Alicate inserção punch down HT314",
    "Testador de cabos NS468",
    "Kit Localizador De Cabos Zumbidor C/ Estojo + Testador",
    "Passa fio com alma 30 metros",
    "Badisco Digital Lcd Com Identificador Chamadas Teste Linha",
    "Estação de solda estanho Ferro Display lcd Desoldering bivolt",
    "Chave Enroladeira/ Desenroladeira para Bloco Bli dupla para telefonia",
  ],
  "Materiais__Técnico de Refrigeração": [
    "Caixa de ferramentas metálica com 05 compartimentos, tratamento antiferrugem, pintura de alta resistência a pó. Medidas aproximadas 50x20x21 cm",
    "Bolsa tipo mala em lona para ferramentas, tamanho mínimo 16 polegadas",
    "Jogo de 8 chaves Fenda com isolamento elétrico 1000 V. Nos tamanhos: 1/8x3, 1/8x4, 3/16x3, 3/16x4, 3/16x6, 1/4x4, 1/4x6, 5/16x6",
    "Jogo de 8 chaves Philips com isolamento elétrico 1000 V. Nos tamanhos: 1/8x3, 1/8x4, 3/16x3, 3/16x4, 3/16x6, 1/4x4, 1/4x6, 5/16x6",
    "Chave Phillips e Fenda Cotoco PHO 1/4 x 1.1/2 Polegadas",
    "Martelo tipo bola 500g cabo em madeira",
    "Lima grosa  meia cana 200 mm com cabo ergonômico e emborrachado",
    "Maçarico portátil profissional com acendimento automático",
    "Gás refil MAP profissional para maçarico portátil 400 g",
    "Chave de fenda Sindal",
    "Alicate universal, acabamento polido, cabo ergonômico emborrachado com abas protetoras. Fabricado em aço carbono, 12”",
    "Alicate de bico reto 6\", indicado para o manuseio de terminais em instalações elétricas e corte de fios e arames macios; possui cabo isolado antiderrapante",
    "Alicate de corte diagonal 6\", indicado para cortar e desencapar fios e cabos elétricos, além de arames macios; com cabo isolado antiderrapante",
    "Chave biela tipo LL n°11. Fabricada em aço e acabamento niquelado e cromado",
    "Estilete profissional retrátil trapezoidal",
    "Kit flangeador exc.1/8 a 3/4 com cortador tubos, chave catraca e escariador",
    "Alargador de tubos cobre e alumínio de 1/8 a 3/4",
    "Cortador De Tubo de 3-16mm Para Tubo Cobre Latão",
    "Manômetro para ar-condicionado. Para Gases R22 e R410",
    "Jogo de chave Allen de 3 a 10 mm, modelo longo, forjado em aço cromo-vanádio e acabamento oxidado",
    "Jogo de Chave Allen Curta de 3/32 a 3/8 Pol",
    "Nível com estrutura de alumínio de alta resistência, escala métrica, tamanho: 12\" (304mm) e bolhas precisas de leitura: vertical, horizontal e 45°",
    "Trena métrica metálica de 5 metros",
    "Termômetro Digital Lcd com sensor",
    "Pulverizador manual de pressão profissional com capacidade mínima de 2 litros",
    "Bolsa/saco coletor de limpeza de ar condicionado ate 30.000 Btus",
    "Pente Para Aletas De Aluminio Ar Condicionado e Evaporadores",
    "Adaptador para mangueira de gás para r410 de 1/4 para 5/16",
    "Voltímetro/amperímetro digital, tipo alicate, 750V/400A. Com capacimetro.  CAT III",
    "Furadeira de impacto 440W/220v",
    "Jogo broca aço rápido SDS Plus, 4mm à 12 mm",
    "Jogo broca para concreto SDS Plus, 6mm à 12 mm",
    "Furadeira e Parafusadeira a bateria 18 v",
    "Jogo de Bits longo para parafusadeira com 2 Bits fenda e 2 Bits philips",
    "Jogo de Bits longo para parafusadeira Soquete Canhão de 5 A 13mm Magnetico",
    "Chave Teste Neon 135mm",
    "Caneta detector de tensão alerta sonoro e luminoso, 12 v a 1000 V AC",
    "Vacuômetro digital para a evacuação de sistemas de refrig. e bombas de calor",
    "Martelo de borracha com cabo em madeira envernizada. Medidas: cabeça 80 mm e comprimento 320 mm",
    "Rebitador manual profissional. Bocal estendido, com chave inclusa na alça, cabo com mola ejeta a haste do rebite e estrutura em aço reforçado",
    "Bomba de vácuo de duplo estágio para geração de vácuo em ar-condicionado",
    "Kit Regulador 2 Vias e Cilindro Co2 4 Kg + Mangueiras 1/4",
    "Kit de solda maçarico PPU oxigênio e acetileno completo",
    "Recolhedor de Gás refrigerante 1HP Bivolt",
    "Tanque cilindro recolhedor de gás refrigerante R22, R410a, R134a Capacidade 13,6 kg",
    "Chave ajustável inglesa 12”.",
    "Chave ajustável inglesa 10”",
    "Varetas para solda Foscoper, 2,5 mm de espessura.",
  ],
  "Uniforme__Eletricista": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
  "Uniforme__Instalador Hidráulico": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
  "Uniforme__Marceneiro": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
  "Uniforme__Pedreiro": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
  "Uniforme__Pintor": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
  "Uniforme__Servente de Obras": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
  "Uniforme__Supervisor": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
  "Uniforme__Técnico de Infraestrutura de Redes": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
  "Uniforme__Técnico de Refrigeração": [
    "Camisa polo, manga curta,em algodão, contendo emblema da empresa",
    "Camiseta, manga longa,contendo punho, em algodão com emblema da empresa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa",
    "Calça em brim pesado, com elástico e cordão na cintura, na cor cinza,",
    "Meia preta em algodão",
    "Botina de segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR 10 - Sem componentes metálicos.",
    "Bota de borracha PVC cano alto",
    "Jaleco operacional manga longa, com punho, em brim pesado, na cor cinza",
    "Moletom (pelúcido), com punho, com emblema da empresa",
    "Jaqueta de inverno, em poliéster e elastano, com zíper, forrada com manta grossa",
    "Camiseta, manga curta, em algodão contendo emblema da empresa (Polo Preta)",
    "Botina de Segurança em microfibra, com elástico, com biqueira de composite, Atendendo NR10 - Sem componentes metálicos",
    "Conjunto de uniforme eletricista NR10 Classe II",
  ],
};

// Colaboradores identificados no Excel (grafias normalizadas)
// CPFs são placeholders — devem ser preenchidos pelo gestor ao confirmar o cadastro
export const COLABORADORES_INICIAIS = [
  { nomeCompleto: "Ivo Leandro da Silva Vieira", cpf: "000.000.000-01", posto: "Marceneiro", dataAdmissao: "2025-03-12", dataDesligamento: null },
  { nomeCompleto: "Andrea dos Santos Pavão", cpf: "000.000.000-02", posto: "Pedreiro", dataAdmissao: "2025-12-03", dataDesligamento: null },
  { nomeCompleto: "Joel Turela Tompsen", cpf: "000.000.000-03", posto: "Técnico de Infraestrutura de Redes", dataAdmissao: "2025-04-07", dataDesligamento: null },
  { nomeCompleto: "Gilberto Texeira da Rosa", cpf: "000.000.000-04", posto: "Pintor", dataAdmissao: "2025-10-13", dataDesligamento: null },
  { nomeCompleto: "Anderson Claiton Lopes da Cruz", cpf: "000.000.000-05", posto: "Eletricista", dataAdmissao: "2025-03-11", dataDesligamento: null },
  { nomeCompleto: "Dilmar Mendes de Souza", cpf: "000.000.000-06", posto: "Eletricista", dataAdmissao: "2025-10-06", dataDesligamento: null },
  { nomeCompleto: "Marcos Vinícius Machado da Silva", cpf: "000.000.000-07", posto: "Técnico de Refrigeração", dataAdmissao: "2025-03-12", dataDesligamento: null },
  { nomeCompleto: "Rogerio Alves", cpf: "000.000.000-08", posto: "Eletricista", dataAdmissao: "2025-12-03", dataDesligamento: null },
  { nomeCompleto: "José Fernando Neves Faller", cpf: "000.000.000-09", posto: "Eletricista", dataAdmissao: "2025-10-06", dataDesligamento: null },
  { nomeCompleto: "Fabiano L. Alves", cpf: "000.000.000-10", posto: "Pedreiro", dataAdmissao: "2025-12-03", dataDesligamento: null },
] as const;
